//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityFastAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Водители
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Водители()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int idВодит { get; set; }
        public string фиоВодит { get; set; }
        public string телВодит { get; set; }
        public string пароль { get; set; }
        public string маркаАвто { get; set; }
        public string номерАвто { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
