//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityFastAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int idЗаказа { get; set; }
        public bool срочныйЗаказ { get; set; }
        public Nullable<System.TimeSpan> времяПриезда { get; set; }
        public string улицаОт { get; set; }
        public string домОт { get; set; }
        public string подъездОт { get; set; }
        public string улицаДо { get; set; }
        public string домДо { get; set; }
        public string подъездДо { get; set; }
        public Nullable<bool> допАдрес { get; set; }
        public string улицаДоп { get; set; }
        public string домДоп { get; set; }
        public string подъездДоп { get; set; }
        public Nullable<bool> перевозкаЖивотн { get; set; }
        public Nullable<bool> детскКресло { get; set; }
        public Nullable<int> ВозрастРебёнка { get; set; }
        public Nullable<bool> некурСалон { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public Nullable<int> idДисп { get; set; }
        public Nullable<int> idКл { get; set; }
        public Nullable<int> idВодит { get; set; }
    
        public virtual Водители Водители { get; set; }
        public virtual Диспетчеры Диспетчеры { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
